---
title: "SMITER: An R Package for SMITE Calibration"
output:
  pkgdown::html_document2:
    template: pkgdown/template/pkgdown.html
---

# SMITER: An R Package for SMITE Calibration

This R package provides functions for SMITE Calibration, including the `SMITE.calib` function.

## Installation

To install the package, you can use the following R code:

- `devtools::install_github("hphughescraft/SMITER")`
- `devtools::install("C:/Users/hphughes/Desktop/Core R/SMITER")`

## User Guide

- **[Start Here](#start-here)**

### Start Here

Welcome to the SMITER User Guide! This guide will help you get started with the SMITER package for SMITE Calibration.

#### Title: SMITER User Guide

#### Release Version: 1.0.0

#### Release Date: January 15, 2024

### Section 2: Getting Started

This section covers the basics of getting started with SMITER.

### Section 3: Advanced Usage

Explore advanced features and use cases of the SMITER package.

### Section 4: FAQ

Frequently asked questions and troubleshooting tips.

... (add more sections as needed)
